version: 0.2

phases:
  install:
    commands:
      - echo =============== Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo =============== Installing dependencies...
      - npm install
      - echo =============== Installing Wine for Ubuntu...
      - dpkg --add-architecture i386
      - wget -qO - https://dl.winehq.org/wine-builds/winehq.key | apt-key add -
      - apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
      - add-apt-repository ppa:cybermax-dexter/sdl2-backport
      #- wget -nc https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/Release.key
      #- apt-key add Release.key
      #- apt-add-repository 'deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./'
      - apt update
      - apt -y install --install-recommends winehq-stable
  build:
    commands:
      - echo =============== Building...
      - npm run electron-pack
artifacts:
  files:
    - "**/*"
  name: portfolio-$(date +%Y-%m-%d)
  discard-paths: no
  base-directory: dist
